import { useState, useMemo } from 'react'
import { Clock, Play, CheckCircle2, Sparkles } from 'lucide-react'
import clsx from 'clsx'
import CollapsibleSection from './CollapsibleSection'
import { useBriefing } from '../../hooks/useBriefing'
import { Spinner } from '../LoadingState'

const SIGNAL_SOURCES = [
  { key: 'tokenSpend', label: 'Token spend & cost trends', defaultOn: true },
  { key: 'crmHealth', label: 'CRM contact health (stale contacts, new contacts)', defaultOn: true },
  { key: 'taskCompletion', label: 'Task completion rate', defaultOn: true },
  { key: 'knowledgeGrowth', label: 'Knowledge base growth', defaultOn: true },
  { key: 'systemHealth', label: 'System health (gateway uptime, cron status)', defaultOn: true },
  { key: 'competitiveIntel', label: 'Competitive intelligence (if available)', defaultOn: true },
  { key: 'youtubeMetrics', label: 'YouTube metrics', defaultOn: false, note: 'Enable when YouTube tab is built' },
  { key: 'socialMedia', label: 'Social media signals', defaultOn: false, note: 'Enable when Research tab is built' },
]

const CHANNELS = [
  { id: '#ops-log', label: '#ops-log' },
  { id: '#general', label: '#general' },
  { id: '#briefing', label: '#briefing' },
]

const SCHEDULE_PRESETS = ['5:00', '5:30', '6:00', '6:30', '7:00', '7:30', '8:00']

const MODELS = [
  { id: 'claude-opus-4.5', label: 'Claude Opus 4.5', costPer1k: 0.03 },
  { id: 'claude-sonnet-4.5', label: 'Claude Sonnet 4.5', costPer1k: 0.009 },
  { id: 'gpt-4o', label: 'GPT-4o', costPer1k: 0.0075 },
]

const REVIEWERS = [
  { key: 'GrowthStrategist', label: 'Growth Strategist', desc: 'Identifies expansion opportunities' },
  { key: 'RevenueGuardian', label: 'Revenue Guardian', desc: 'Evaluates financial impact and ROI' },
  { key: 'SkepticalOperator', label: 'Skeptical Operator', desc: 'Challenges assumptions, verifies data' },
  { key: 'TeamDynamicsArchitect', label: 'Team Dynamics Architect', desc: 'Assesses staffing and morale impact' },
]

function Toggle({ checked, onChange }) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      className={clsx('relative h-6 w-11 rounded-full transition-colors', checked ? 'bg-accent' : 'bg-surface-600')}
    >
      <span
        className="absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-transform"
        style={{ left: 2, transform: checked ? 'translateX(21px)' : 'translateX(0)' }}
      />
    </button>
  )
}

export default function BriefingSection({ briefing, onUpdate }) {
  const { generating, generateNow } = useBriefing()
  const [generateSuccess, setGenerateSuccess] = useState(false)

  function handleGenerateNow() {
    generateNow()
    setGenerateSuccess(false)
    setTimeout(() => setGenerateSuccess(true), 1600)
    setTimeout(() => setGenerateSuccess(false), 4000)
  }

  const signals = briefing.signals || {}
  const council = briefing.council || {}
  const reviewers = council.reviewers || {}
  const weights = council.weights || { impact: 0.4, confidence: 0.35, effort: 0.25 }

  function isSignalChecked(key) {
    if (key in signals) return signals[key]
    return SIGNAL_SOURCES.find((s) => s.key === key)?.defaultOn ?? false
  }

  function toggleSignal(key) {
    onUpdate({ signals: { [key]: !isSignalChecked(key) } })
  }

  function setWeight(key, val) {
    const clamped = Math.max(0, Math.min(1, val))
    const others = Object.entries(weights).filter(([k]) => k !== key)
    const remaining = 1 - clamped
    const otherSum = others.reduce((s, [, v]) => s + v, 0)
    const newWeights = { [key]: Math.round(clamped * 100) / 100 }
    for (const [k, v] of others) {
      newWeights[k] = otherSum > 0 ? Math.round((v / otherSum) * remaining * 100) / 100 : Math.round((remaining / others.length) * 100) / 100
    }
    const sum = Object.values(newWeights).reduce((s, v) => s + v, 0)
    if (Math.abs(sum - 1) > 0.01) {
      const firstOther = others[0][0]
      newWeights[firstOther] = Math.round((newWeights[firstOther] + (1 - sum)) * 100) / 100
    }
    onUpdate({ council: { weights: newWeights } })
  }

  const selectedModel = MODELS.find((m) => m.id === (council.model || 'claude-opus-4.5')) || MODELS[0]
  const estimatedCost = useMemo(() => {
    const approxTokens = 28_000
    return (approxTokens / 1000) * selectedModel.costPer1k
  }, [selectedModel])

  const disabled = !briefing.enabled

  return (
    <CollapsibleSection
      icon={Sparkles}
      title="Daily Briefing"
      subtitle="Configure the AI-powered business briefing generated by Jinx"
    >
      <div className="space-y-6">
        {/* ── Schedule ────────────────────────────────── */}
        <div className="space-y-4">
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-600">Schedule</p>

          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-gray-300">Enable Daily Briefing</p>
              <p className="mt-0.5 text-[10px] text-gray-600">Jinx generates a morning analysis at the scheduled time</p>
            </div>
            <Toggle checked={briefing.enabled} onChange={(v) => onUpdate({ enabled: v })} />
          </div>

          <div className={clsx(disabled && 'opacity-50 pointer-events-none')}>
            <label className="mb-1.5 block text-xs font-medium text-gray-400">Generation Time</label>
            <div className="flex items-center gap-3">
              <input
                type="time"
                value={briefing.scheduleTime}
                onChange={(e) => onUpdate({ scheduleTime: e.target.value })}
                className="settings-input w-32"
              />
              <span className="text-xs text-gray-600">daily</span>
            </div>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {SCHEDULE_PRESETS.map((time) => (
                <button
                  key={time}
                  onClick={() => onUpdate({ scheduleTime: time })}
                  className={clsx(
                    'rounded-md px-2.5 py-1 text-[11px] font-medium transition-colors',
                    briefing.scheduleTime === time ? 'bg-accent/15 text-accent' : 'bg-surface-700 text-gray-400 hover:bg-surface-600 hover:text-gray-300'
                  )}
                >
                  {formatTime12(time)}
                </button>
              ))}
            </div>
          </div>

          <div className={clsx(disabled && 'opacity-50 pointer-events-none')}>
            <label className="mb-1.5 block text-xs font-medium text-gray-400">Delivery Channel</label>
            <select
              value={briefing.channel}
              onChange={(e) => onUpdate({ channel: e.target.value })}
              className="settings-select w-40"
            >
              {CHANNELS.map((ch) => (
                <option key={ch.id} value={ch.id}>{ch.label}</option>
              ))}
            </select>
            <p className="mt-1 text-[10px] text-gray-600">Briefing will be posted to this Discord channel</p>
          </div>
        </div>

        {/* ── Signal Sources ──────────────────────────── */}
        <div className={clsx(disabled && 'opacity-50 pointer-events-none')}>
          <p className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-gray-600">Signal Sources</p>
          <div className="space-y-2">
            {SIGNAL_SOURCES.map((opt) => (
              <label key={opt.key} className="flex items-center gap-2.5 cursor-pointer group">
                <input
                  type="checkbox"
                  checked={isSignalChecked(opt.key)}
                  onChange={() => toggleSignal(opt.key)}
                  className="h-3.5 w-3.5 rounded border-surface-500 bg-surface-800 text-accent focus:ring-accent/30 focus:ring-offset-0"
                />
                <span className="text-xs text-gray-300 group-hover:text-gray-200">{opt.label}</span>
                {opt.note && (
                  <span className="rounded-full bg-surface-700 px-1.5 py-0.5 text-[9px] text-gray-500">{opt.note}</span>
                )}
              </label>
            ))}
          </div>
        </div>

        {/* ── Council Configuration ───────────────────── */}
        <div className={clsx(disabled && 'opacity-50 pointer-events-none', 'space-y-4')}>
          <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-600">Council Configuration</p>

          <div>
            <label className="mb-1.5 block text-xs font-medium text-gray-400">Model for All Phases</label>
            <select
              value={council.model || 'claude-opus-4.5'}
              onChange={(e) => onUpdate({ council: { model: e.target.value } })}
              className="settings-select w-52"
            >
              {MODELS.map((m) => (
                <option key={m.id} value={m.id}>{m.label}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="mb-2 block text-xs font-medium text-gray-400">Reviewers</label>
            <div className="space-y-2">
              {REVIEWERS.map((r) => (
                <label key={r.key} className="flex items-center gap-2.5 cursor-pointer group">
                  <input
                    type="checkbox"
                    checked={reviewers[r.key] !== false}
                    onChange={() => onUpdate({ council: { reviewers: { [r.key]: !(reviewers[r.key] !== false) } } })}
                    className="h-3.5 w-3.5 rounded border-surface-500 bg-surface-800 text-accent focus:ring-accent/30 focus:ring-offset-0"
                  />
                  <div>
                    <span className="text-xs text-gray-300 group-hover:text-gray-200">{r.label}</span>
                    <span className="ml-2 text-[10px] text-gray-600">{r.desc}</span>
                  </div>
                </label>
              ))}
            </div>
          </div>

          <div>
            <label className="mb-2 block text-xs font-medium text-gray-400">Priority Weights</label>
            <div className="space-y-3">
              {[
                { key: 'impact', label: 'Impact' },
                { key: 'confidence', label: 'Confidence' },
                { key: 'effort', label: 'Effort (inverted)' },
              ].map(({ key, label }) => (
                <div key={key} className="flex items-center gap-3">
                  <span className="text-[11px] text-gray-400 w-28 shrink-0">{label}</span>
                  <input
                    type="range"
                    min={0}
                    max={100}
                    value={Math.round((weights[key] || 0) * 100)}
                    onChange={(e) => setWeight(key, Number(e.target.value) / 100)}
                    className="flex-1 accent-accent h-1.5"
                  />
                  <span className="text-[11px] font-medium text-gray-300 w-10 text-right">{(weights[key] || 0).toFixed(2)}</span>
                </div>
              ))}
            </div>
            <div className="mt-2 rounded-lg bg-surface-800/50 px-3 py-2">
              <p className="text-[10px] text-gray-500 font-mono">
                Priority = (Impact × {weights.impact?.toFixed(2)}) + (Confidence × {weights.confidence?.toFixed(2)}) + ((100 - Effort) × {weights.effort?.toFixed(2)})
              </p>
            </div>
          </div>
        </div>

        {/* ── Generate & Cost ─────────────────────────── */}
        <div className="border-t border-surface-800 pt-4 space-y-3">
          <div className="flex items-center gap-3">
            <button
              onClick={handleGenerateNow}
              disabled={generating}
              className={clsx(
                'flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-medium transition-colors',
                generating ? 'bg-surface-700 text-gray-500 cursor-not-allowed' : 'bg-accent/10 text-accent hover:bg-accent/20'
              )}
            >
              {generating ? <Spinner className="h-3.5 w-3.5" />
                : generateSuccess ? <CheckCircle2 className="h-3.5 w-3.5 text-status-online" />
                : <Play className="h-3.5 w-3.5" />}
              {generating ? 'Generating...' : generateSuccess ? 'Briefing generated!' : 'Generate Now'}
            </button>
            <span className="text-[10px] text-gray-600">Runs the briefing immediately for testing</span>
          </div>

          <div className="rounded-lg bg-surface-800/50 px-3 py-2.5 flex items-center gap-2">
            <Clock className="h-3.5 w-3.5 text-gray-600 shrink-0" />
            <p className="text-[11px] text-gray-500">
              Estimated cost: <span className="font-medium text-gray-300">~${estimatedCost.toFixed(2)}</span> per briefing using {selectedModel.label}
            </p>
          </div>
        </div>
      </div>
    </CollapsibleSection>
  )
}

function formatTime12(time24) {
  if (!time24) return '—'
  const [h, m] = time24.split(':').map(Number)
  const ampm = h >= 12 ? 'PM' : 'AM'
  const h12 = h === 0 ? 12 : h > 12 ? h - 12 : h
  return `${h12}:${String(m).padStart(2, '0')} ${ampm}`
}
